spring.application.name=api-gateway

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server.port=9191
management.endpoints.web.exposure.include=*

## routes for employee service
#spring.cloud.gateway.routes[0].id=worker-service
#load balancing url
#spring.cloud.gateway.routes[0].uri=lb://worker-service
#original url, if we give this one, need to give lb separately
#spring.cloud.gateway.routes[0].uri=http://localhost:8081
#spring.cloud.gateway.routes[0].predicates[0]=Path=/api/workers/**

## routes for department service
#spring.cloud.gateway.routes[1].id=department-service
#spring.cloud.gateway.routes[1].uri=lb://department-service
#spring.cloud.gateway.routes[1].predicates[0]=Path=/api/departments/**

## client requesting url will be= http://localhost:9191/api/workers

#automtic configuration
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
logging.level.org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping=DEBUG

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.handler=DEBUG
logging.level.org.springframework.cloud.gateway.route=DEBUG
logging.level.org.springframework.cloud.gateway.filter=DEBUG
